# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 22:49
from __future__ import unicode_literals

from django.db import migrations




class Migration(migrations.Migration):

    dependencies = [
        ('movieratings_app', '0002_auto_20170316_2240'),
    ]

    operations = [
    ]
