# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings_app', '0005_auto_20170317_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
