# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 17:28

from __future__ import unicode_literals

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('movieratings_app', '0007_auto_20170317_1456'),
    ]

    operations = [

    ]
