# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 17:28

from __future__ import unicode_literals
from movieratings_app.models import Rater
from django.db import migrations
from django.contrib.auth.models import User
import random


def create_users(apps, schema_editor):
    all_raters = Rater.objects.all()
    poss_first_names = ['Will', 'William', "Elaine", "Deborah", "Keyshawn", "Monique", "Sarah", "Billiam", 'Bill', 'Billy', 'Billie', 'Graham',
                        "David", "Algernon", "Warren", "David"]

    poss_last_names = ['Brown', "Johnson", "Cota", "Jordan", "Carter", "Montross", "Hansbrough",
                        "Jamison", "Felton", "Lawson", "Paige", "Barnes", "Zwikker", "Henson"]
    poss_email = ['@gsnails.com', "@acc.edu", "@theceilingistheroof.com"]
    n = 10000
    suffix = []
    while n > 0:
        suffix.append(n)
        n -= 1
    for rater in all_raters:
        user_id = rater.id
        first_name = random.choice(poss_first_names)
        last_name = random.choice(poss_last_names)
        username = (str(first_name)+str(last_name))+str(suffix.pop(-1))
        email = (str(username)+random.choice(poss_email))
        password="smokecrack"
        user = User.objects.create_user(id=user_id, username=username, email=email, password=password,
               first_name=first_name, last_name=last_name)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings_app', '0008_auto_20170319_1728'),
    ]

    operations = [
        migrations.RunPython(create_users)
    ]
